=== Darikiva/labs/semester5/OOP/lab2/Gems/gems.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="nameType">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>


    <xs:simpleType name="preciousnessChoice">
        <xs:restriction base="xs:string">
            <xs:enumeration value="precious"/>
            <xs:enumeration value="semiprecious"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="preciousnessType">
        <xs:attribute name="value" type="preciousnessChoice" use="required"/>
    </xs:complexType>

    <xs:complexType name="originType">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blue"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="green"/>
            <xs:enumeration value="magenta"/>
            <xs:enumeration value="white"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="transparencyType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="edgesType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="4"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="visualParametersType">
        <xs:attribute name="color" type="colorType" use="required"/>
        <xs:attribute name="transparency" type="transparencyType" use="required"/>
        <xs:attribute name="edges" type="edgesType" use="required"/>
    </xs:complexType>

    <xs:complexType name="weightType">
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="gemType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="preciousness" type="preciousnessType"/>
            <xs:element name="origin" type="originType"/>
            <xs:element name="visualParameters" type="visualParametersType"/>
            <xs:element name="weight" type="weightType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="gems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gem" type="gemType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Darikiva/labs/semester5/lab2/Gems/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="gems.xsd"
>

    <gem id="1">
        <name value="dfl"/>
        <preciousness value="semiprecious"/>
        <origin value="string"/>
        <visualParameters color="red" transparency="3" edges="4"/>
        <weight value="3"/>
    </gem>

    <gem id="2">
        <name value="Amethyst"/>
        <preciousness value="semiprecious"/>
        <origin value="Rubizhne"/>
        <visualParameters color="magenta" transparency="50" edges="10"/>
        <weight value="50"/>
    </gem>

    <gem>
        <name value="diamond"/>
        <preciousness value="precious"/>
        <origin value="Kyiv"/>
        <visualParameters color="white" transparency="90" edges="15"/>
        <weight value="2"/>
    </gem>

    <gem>
        <fds></fds>
        <name value="asdf"/>
        <preciousness value="precious"/>
        <origin value="asdf"/>
        <visualParameters color="red" transparency="3" edges="5"/>
        <weight value="3"/>
    </gem>

</gems>
